spring:
  freemarker:
    cache: false
    settings:
      auto_import: /spring.ftl as spring
  datasource:
    url: jdbc:mysql://localhost:3307/richscan?useSSL=false&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:templates
      suffix: .ftl